// on git push trigger build event
properties([pipelineTriggers([pollSCM('H * * * *')])])

// node to be built on
node {
	// var commit
	def commit_id

	stage('Preparation') {
		// git checkout software configuration management
		checkout scm
		// get the commit id and store it in .git/commit-id
		sh "git rev-parse --short HEAD > .git/commit-id"
		// commit id = the contents of the created file (trimming the white space out)
		commit_id = readFile('.git/commit-id').trim()
	}	

	stage('docker build/push') {
		// we want to use the docker registry using the credentials stored in 'dockerhub'
		docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
			// build & push to selected registry
			def app = docker.build("simuha999/portfolio:${commit_id}", './web/react').push()
		}
	}
}